services:
    auth.provider.oneall_singlesignon:
        class: oneall\singlesignon\auth\provider\oneall
        arguments:
            - '@dbal.conn'
            - '@config'
            - '@passwords.manager'
            - '@request'
            - '@user'
            - '@service_container'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: auth.provider }
